#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/geojson-extension jupyterlab-drawio
jupyter labextension install @jupyterlab/toc
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git